booksnob/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from critic.views import ReviewView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^critic/', include('critic.urls')),
    url(r'^', include('reader.urls')),
    url(r'^reader/', include('reader.urls')),
    
]

booksnob/critic/urls.py
"""Dj URL Configuration for critic


"""
from django.conf.urls import url


from critic import views

urlpatterns = [
    url(r'^review/$', views.ReviewView.as_view(), name = 'review_book'),
    url(r'^thanks/$', views.ThanksView.as_view()),
    url(r'^see_reviews_list/$', views.SeeReviewsList.as_view(), name = 'see_reviews_list'),
    url(r'^see_reviews_list/(?P<pk>\d+)/$', views.SeeOneReview.as_view(), name = 'see_one_review'),
]

booksnob/reader/urls.py
"""Dj URL Configuration for taestapp


"""
from django.conf.urls import url


from reader import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view()),
    url(r'^get_author/$', views.Form.as_view(), name='get_author'),
    url(r'^thanks/$', views.ThanksView.as_view(), name='info'),
    url(r'^get_author/(?P<pk>\d+)/$', views.GetAuthorView.as_view()),
    url(r'^get_author/get_list/$', views.GetAuthorList.as_view()),
    url(r'^get_author/get_list/(?P<pk>\d+)/$', views.OneAuthorView.as_view(), name='one_author'),
]

booksnob/reader/models.py
from django.db import models
from reader.manager import AuthorManager

class Author(models.Model):
	first_name=models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField()
	filter_author = AuthorManager
	objects = models.Manager
	
	def __unicode__(self):
 		return '{0} {1}'.format(self.first_name, self.last_name)


class Book(models.Model):
	author = models.ForeignKey(Author)
	name = models.CharField(max_length=100)

	def __unicode__(self):
		return '{0} - {1}'.format(self.author.last_name, self.name)

class Review(models.Model):
	book = models.ForeignKey(Book)	
	text = models.CharField(max_length=1000)
	def __unicode__(self):
		return '{0} - {1}'.format(self.book.name, self.text)

class Reader(models.Model):
	book = models.ManyToManyField(Book)
	first_name = models.CharField(max_length = 50)
	last_name = models.CharField(max_length = 50)

	def __unicode__(self):
		return '{0} - {1}'.format(self.name, self.book.name )

		

booksnob/critic/forms.py
from django import forms

from reader.actions import get_books1

class ReviewForm(forms.Form):
	book_name = forms.ChoiceField(choices=[(book, book) for book in get_books1()])
	text = forms.CharField(widget=forms.Textarea)

	def send_email(self):
		print('Book: {0}'.format(self.cleaned_data['book_name']))
		print('Message: {0}'.format(self.cleaned_data['text']))	

booksnob/reader/forms.py
from reader.models import Author
from django.forms import ModelForm

class AuthorForm(ModelForm):
	class Meta:
		model = Author
		fields = ['first_name', 'last_name', 'email']

booksnob/critic/views.py
from critic.forms import ReviewForm
from django.views.generic.edit import FormView
from django.views.generic import TemplateView, DetailView, ListView
from reader.models import Review, Book

class ReviewView(FormView):
	form_class = ReviewForm
	template_name = 'critic/review.html'
	success_url = '/critic/thanks/'
	"""
	def post(self,request, *args, **kwargs):
	"""

	def form_valid(self, form):
		form.send_email()
		text = form.cleaned_data['text']
		book_name = form.cleaned_data['book_name']	
		print book_name	
		book_name = book_name.split('- ')
		print book_name		
		book_name_id = Book.objects.filter(name = book_name[1]).values()
		got_book_name_id=[]
		for i in book_name_id:
			got_book_name_id.append(i['id'])
			print i			
		review = Review.objects.create(
			text = text,
			book_id = got_book_name_id[0],)

		return super(ReviewView, self).form_valid(form)	
	
class ThanksView(TemplateView):
	template_name = 'critic/thanks.html'     

class SeeReviewsList(ListView):
	model = Review	
	template_name = 'critic/see_reviews_list.html'	  

class SeeOneReview(DetailView):
	model = Review
	template_name = 'critic/see_one_review.html'	 

booksnob/reader/views.py
from django.views.generic import TemplateView, DetailView, ListView
from reader.manager import AuthorManager
from reader.actions import get_books, get_authors
from reader.forms import AuthorForm
from django.http.request import HttpRequest
from django.http import HttpResponse
from reader.models import Author

from django.views.generic.edit import FormView 

class HomeView(TemplateView):
	template_name = 'base.html'
	

class HomeView(TemplateView):
	template_name = 'reader/home.html'

	def get_context_data(self, **kwargs):
		context = super(HomeView,self).get_context_data(**kwargs)
		context['author_name'] = get_authors()
		context['books'] = get_books()

		return context


class Form(FormView):
	form_class = AuthorForm
	template_name = 'reader/get_authors.html'
	success_url = '/reader/thanks/'
	"""
	def post(self,request, *args, **kwargs):
	"""
	def form_valid(self,form):
		self.object=form.save()
		print self.object
		return super(Form, self).form_valid(form)


class ThanksView(TemplateView):
    template_name = 'reader/thanks.html'

class GetAuthorView(DetailView):
	model = Author
	template_name = 'reader/authors.html'
	"""

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(GetAuthorView, self).get_context_data(**kwargs)
		# Add in a QuerySet of all the books
		context['book_list'] = Author.objects.all()
		return context
	"""
class OneAuthorView(DetailView):
	model = Author
	template_name = 'reader/one_author.html'



class GetAuthorList(ListView):
	model = Author
	
	template_name = 'reader/get_list.html'

booksnob/templates/base.html
<!DOCTYPE>
<html lang="en">
<head>
	<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
    <style>
        .container-fluid {height:600px;}
        .wrapper {background-color: rgba(112, 106, 141, 0.43);
                    height: 200px;
                    margin-top: 63px;
        }
        .wrapper p {padding-top: 35px;}
    </style>
    </head>
    

<body>
    <h1 class="text-center text-uppercase text-success">Welcom to my app</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <div class="wrapper">
        <p class="text-center">Thanks for visiting my site.</p>
    </div>    
    {% endblock %}
</body>
</html>

booksnob/templates/critic/review.html
{% extends 'base.html' %}
{% block content %}

	<div class="container-fluid">
		<p>	
		{{ form.errors }}
		</p>
		<form action ='{% url "review_book" %} ' method = "post">
			<div class="row">
				<div class="col-xs-6">
					{% csrf_token %}
					<h1 class="bg-primary text-center">First, select a book</h1>
					<label for = "book_names">Book name:</label>
					<select id = "book_names" name = "book_name">
							{% for val, txt in form.fields.book_name.choices %}
								
							<option value="{{ val }}">{{ txt }}</option>
								{% endfor %}
							
					</select>

				</div>
						<div class="col-xs-6">
							<h1 class="bg-primary text-center" >Write your review there</h1>
							
							<textarea id = "id_text"  name = "text">{{ form.form.text }}
							</textarea>
						
					<input type = "submit" value = "Send" class=" btn-info btn-sm my_button" />
					</div>	
				</form>	
			
		</div>
		<a class="btn btn-success btn-lg" href="/" role="button">Go Back</a>	
		<a class="btn btn-success btn-lg" href="/critic/see_reviews_list" role="button">See existing reviews list</a>	

	</div>		
{% endblock %}

booksnob/templates/critic/see_one_review.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<ul class="list-group">
		<li class="list-group-item hidden_li">{{ review }}</li>
	</ul>
</div>	
{% endblock %}

booksnob/templates/critic/see_reviews_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	{% for review in review_list %}
	<ul class="list-group">		
		<li class="list-group-item hidden_li">
			<a href="{% url 'see_one_review' review.pk %}">{{ review }}</a>
		</li>
	</ul>
{% endfor %}
</div>	

{% endblock %}

booksnob/templates/critic/thanks.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<a class="btn btn-success btn-lg" href="/critic/see_reviews_list" role="button">See reviews list</a>	
	<a class="btn btn-success btn-lg" href="/critic/review/" role="button">Go Back</a>
</div>		
{% endblock %}

booksnob/templates/reader/authors.html
{% extends 'base.html' %}
{% block content %}
{{ author }}
{% endblock %}

booksnob/templates/reader/get_authors.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<form action='{% url "get_author" %} ' method="POST">
		<fieldset>
    	<legend>Introduce yourself</legend>	
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="btn btn-success"/>
		</fieldset>
	</form>
</div>		
{% endblock %}

booksnob/templates/reader/get_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<h2>Choose the author below:</h2>
	{% for author in author_list %}
	<ul class="list-group">		
		<li class="list-group-item hidden_li"><a href="{% url 'one_author' author.pk %}">{{ author }}</a></li>
		
	</ul>
	{% endfor %}
	<a class="btn btn-success btn-lg" href="/" role="button">Main Page</a>
</div>


{% endblock %}

booksnob/templates/reader/home.html
{% extends 'base.html' %}
{% block content %}
<style>
	.with_margin {margin-top: 6px;}
</style>
	<div class="container-fluid">
       <div class="row">
			<div class="col-xs-8">
				<h1 class="bg-primary text-center roww">Books:</h1>
				<ul class="list-group">	
				{% for authors, books in books.items %}
					<li class="list-group-item hover_li">
					{{ authors }}
						<ul class="list-group">
						{% for book in books %}
							<li class="list-group-item hidden_li">{{ book }}</li>
							{% empty %}
							<li class="list-group-item">No books</li>
							{% endfor %}
						</ul>
					</li>
				{% empty %}
					<li class="list-group-item">No Authors</li>	
				{% endfor %}
				</ul>
			<a class="btn btn-info btn-lg" href="/get_author" role="button">Add a new book</a>		
			<a class="btn btn-info btn-lg" href="/critic/review" role="button">Do a book review</a>		
			<a class="btn btn-info btn-lg" href="/critic/see_reviews_list/" role="button">See existing reviews</a>	
			     	
			
			</div>
			<div class="col-xs-4">
				<h1 class="bg-primary text-center">Authors:</h1>
				<ul class="list-group">
					{% for author in author_name %}
						<li class="list-group-item">{{ author }}</li>		
					{% empty %}
						<li>No authors</li>
					{% endfor %}

				</ul>
				<a class="btn btn-info btn-lg with_margin" href="/get_author" role="button">Add a new author</a>
				<a class="btn btn-info btn-lg with_margin" href="/get_author/get_list" role="button">meet the author closer</a>	
			</div>
		</div>
    </div>
{% endblock %}

booksnob/templates/reader/one_author.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<ul class="list-group">
		<li class="list-group-item hidden_li">{{ author }}</li>
	</ul>
	<a class="btn btn-success btn-lg" href="/" role="button">Main Page</a>
</div>	
{% endblock %}

booksnob/templates/reader/thanks.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
	<h2 class="bg">Success.You will see yourself on the main page.
	</h2>	
	<a class="btn btn-success btn-lg" href="/get_author" role="button">Go Back</a>	
	<a class="btn btn-success btn-lg" href="/" role="button">Main Page</a>
</div>		
{% endblock %}